version: '2'

vars:
  ALPVER: 3.13
  GOVER: 1.16
  KAFKAVER: 1.5.0

tasks:
  build-alpine:
    desc: Build alpine image
    cmds:
      - docker build -t unitedwardrobe/alpine-golang:{{.TAG}} ./alpine-golang/{{.TAG}}
    vars:
      TAG: alpine{{.ALPVER}}-golang{{.GOVER}}

  push-alpine:
    desc: Push alpine image
    cmds:
      - docker push unitedwardrobe/alpine-golang:{{.TAG}}
    vars:
      TAG: alpine{{.ALPVER}}-golang{{.GOVER}}

  build-alpine-librdkafka:
    desc: Build alpine librdkafka image
    cmds:
      - docker build -t unitedwardrobe/golang-librdkafka:{{.TAG}} ./alpine-golang-librdkafka/{{.TAG}}
    vars:
      TAG: alpine{{.ALPVER}}-golang{{.GOVER}}-librdkafka{{.KAFKAVER}}

  push-alpine-librdkafka:
    desc: Push alpine librdkafka image
    cmds:
      - docker push unitedwardrobe/golang-librdkafka:{{.TAG}}
    vars:
      TAG: alpine{{.ALPVER}}-golang{{.GOVER}}-librdkafka{{.KAFKAVER}}

  build-alpine-librdkafka-static:
    desc: Build alpine static image
    cmds:
      - docker build -t unitedwardrobe/golang-librdkafka:{{.TAG}} ./alpine-golang-librdkafka/{{.TAG}}
    vars:
      TAG: alpine{{.ALPVER}}-golang{{.GOVER}}-librdkafka{{.KAFKAVER}}-static

  push-alpine-librdkafka-static:
    desc: Push alpine static image
    cmds:
      - docker push unitedwardrobe/golang-librdkafka:{{.TAG}}
    vars:
      TAG: alpine{{.ALPVER}}-golang{{.GOVER}}-librdkafka{{.KAFKAVER}}-static

  build-circle:
    desc: Build Circle image
    cmds:
      - docker build -t unitedwardrobe/golang-librdkafka:{{.TAG}} ./circle-golang-librdkafka/{{.TAG}}
    vars:
      TAG: circle-golang{{.GOVER}}-librdkafka{{.KAFKAVER}}

  push-circle:
    desc: Push Circle image
    cmds:
      - docker push unitedwardrobe/golang-librdkafka:{{.TAG}}
    vars:
      TAG: circle-golang{{.GOVER}}-librdkafka{{.KAFKAVER}}